import Button from './Button.jsx'

/*EXTERNAL METHOD*//*FOR GLOBAL STYLES OR SMALL PROJECTS*/
/*MODULES METHOD*//*FOR (BIG PROJECTS USUALLY) INDIVIDUAL COMPONENTS THAT HAVE THEIR OWN UNIQUE STYLES*/
/*INLINE METHOD*//*FOR SMALL COMPONENTS WITH MINIMAL STYLING*/

function App() {

  return (<Button />);
}

export default App
